apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-app
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami-app
  template:
    metadata:
      labels:
        app: whoami-app
    spec:
      containers:
      - name: whoami-app
        image: whoami-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-app
  namespace: development
spec:
  selector:
    app: whoami-app
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP
