apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-development
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: efrei2023/my-go-app:latest
          ports:
            - containerPort: 8181
          imagePullPolicy: IfNotPresent  
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: prod
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
  type: NodePort
